version: '3.11'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    environment:
      - FASTAPI_ENV=development

  db:
    image: "sqlite"
    container_name: "sqlite_db"
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=/data/addressbook.db
